project:
  type: website
  output-dir: docs

website:
  title: "Camila Pastén"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true
