project:
  type: website
  output-dir: docs

website:
  title: "Camila Pastén"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: Materia
        menu:
          - href: Persona_Equipo/index.qmd
            text: Persona y Equipo

format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true
