project:
  type: website
  output-dir: docs

website:
  title: "Camila Pastén"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Material
        menu:
          - text: Persona y Equipo
            href: Material/Persona_Equipo/index.qmd
          - text: Contabilidad II
            href: Material/Contabilidad_II/index.qmd
          - text: Estrategias
            href: Material/Estrategias/index.qmd
          - text: Fundamentos de Administración
            href: Material/Fundamentos_Administracion/index.qmd
          - text: Programación
            href: Material/Programacion/index.qmd
          - text: Tecnología y Empresas
            href: Material/Tecnologia_Empresas/index.qmd

format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true
