project:
  type: website
  output-dir: docs

website:
  title: "Camila Pastén"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: Persona_Equipos.qmd
        text: Persona y Equipos
      - href: Robbins_Judge_Cap1_Comportamiento_Organizacional.qmd
        text: Capítulo 1: Comportamiento Organizacional
      - href: Robbins_Judge_Cap2_Diversidad.qmd
        text: Capítulo 2: Diversidad

format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true