project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: CV
        text: Curriculum Vitae
      - text: Material
        menu:
          - href: Material/Conta_II/index.qmd
            text: Contabilidad II
          - href: Material/Estrategia/index.qmd
            text: Estrategias
          - href: Material/FAN_II/index.qmd
            text: Fundamentos Administrativos
          - href: Material/PyE/index.qmd
            text: Persona y Equipo
          - href: Material/Progra/index.qmd
            text: Programación
          - href: Material/TyE/index.qmd
            text: Tecnología y Empresas


format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: false
