project:
  type: website
  output-dir: docs

website:
  title: "Camila Pastén"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: Material
        menu:
          - href: Material/Persona_Equipo/index.qmd
            text: Persona y Equipo

format:
  html:
    theme: cosmo
    toc: true
